name: Validate Markdown

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate README
      run: |
        grep -E '^\[([0-9]+)\]\s+([^\(]+)\s+\((https://www.linkedin.com/in/[^\)]+)\)$' -o README.md || true

    - name: Success message
      if: ${{ success() }}
      run: |
        echo "Markdown no README.md segue o formato esperado!"

    - name: Failure message
      if: ${{ failure() }}
      run: |
        echo "O item no README.md não segue o formato esperado. Por favor, revise o formato e envie novamente."
