name: Validate README.md

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  
  workflow_dispatch:

jobs:
  validate-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate README.md
      run: |
        # Obtém todas as linhas após a seção ### Alunos
        alunos_lines=$(awk '/^### Alunos$/,0' README.md | tail -n +2)

        # Itera sobre as linhas e verifica o formato
        echo "$alunos_lines" | while read -r line; do
          # Verifica se a linha segue o formato esperado
          if ! echo "$line" | grep -E -q '^[0-9]{2}\. \[.+\]\(https:\/\/www\.linkedin\.com\/in\/.+\)$'; then
            echo "Erro: A seguinte linha após ### Alunos não está no formato correto:"
            echo "$line"
            exit 1
          fi
        done

        echo "Todas as linhas após ### Alunos estão no formato correto."
