name: Validate Markdown

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate README
      run: |
        grep -E '^\[([0-9]+)\]\s+([^\(]+)\s+\((https://www.linkedin.com/in/[^\)]+)\)$' README.md

    - name: Comment on PR
      if: ${{ failure() }}
      uses: mb2dev/github-action-comment-pull-request@1.0.0
      with:
        token: ${{ secrets.TOKEN_GITHUB }}
        body: "O item no README.md não segue o formato esperado. Por favor, revise o formato e envie novamente."