name: Validate README.md

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  validate-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate README.md
      run: |
        # Captura as linhas adicionadas nos commits
        added_lines=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs git show | grep "+++" | sed 's/+++ b\///')

        # Verifica se README.md está entre os arquivos alterados
        if echo "$added_lines" | grep -q '^README\.md$'; then
          # Verifica se todas as linhas adicionadas seguem o formato esperado
          if grep -E -q '^[0-9]{2}\. \[.+\]\(https:\/\/www\.linkedin\.com\/in\/.+\)$' README.md; then
            echo "README.md está no formato correto."
          else
            echo "Erro: README.md não está no formato correto."
            exit 1
          fi
        else
          echo "Nenhuma alteração em README.md detectada."
        fi