name: Validate README

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  
  workflow_dispatch:

jobs:
  validate-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate README
      run: |
        # Extrai linhas após a seção ### Alunos no README.md
        alunos_lines=$(sed -n -e '/### Alunos/,$p' README.md | sed '1d')

        # Itera sobre as linhas e verifica o formato
        while read -r line; do
          # Verifica se a linha segue o formato esperado
          if ! echo "$line" | grep -E -q '^[0-9]{2}\. \[.+\]\(https:\/\/www\.linkedin\.com\/in\/.+\/)$'; then
            echo "Erro: A seguinte linha após ### Alunos não está no formato correto:"
            echo "$line"
            exit 1
          else
            echo "Sucesso: A seguinte linha após ### Alunos está no formato correto:"
            echo "$line"
          fi
        done <<< "$alunos_lines"
